apiVersion: v1
kind: Pod
metadata:
  name: startup
spec:
  containers:
  - name: frontend2
    image: brainupgrade/sba-frontend:base
    startupProbe:
      httpGet:
        path: /healthz
        port: 8080
      initialDelaySeconds: 0
      periodSeconds: 10
      successThreshold: 1
      failureThreshold: 3



