apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: harishpandu43/sba-frontend
        env:
        - name: REACT_APP_API_URL
          value: "https://scbcepb3u18-app.brainupgrade.net/api/"
        ports:
        - containerPort: 3000